# (PART\*) Introduction {-}

# Purpose {-}

The purpose of this guide is to introduce you to the tools and methodologies that at the ERPI and LF2L laboratory, we use in our daily basis. 
This is an introductory guide to the different steps that we consider you will have to do as young research intern in the following months with us. 

Even if the steps are general, We hope these elements could be helpful for you during and after your internship.


## Intended outcomes {-}

At the end of you internship, we hope that you will be able to:

* Understand the process of create scientific documents.
* Have a first insight in the data visualization practices using datasets.
* Experience the diversity of options that open practices offers to communicate your results. 

::: {.infobox .tip data-latex="{note}"}
There are many references and information  within this practical workshop book and **we do not expect you to read everything we link to**. 

However, this is a first step in order to get competence in the scientific research path. 
Do be scare to use different tools other than you have know so far. 

Good luck!
:::

The lectures and practical links of this guide will only form a part of the learning process. 
You are invited to undertake wider reading and explore new methods and approaches. 







